name: health_monitor_app
description: A Flutter app for health monitoring via BLE

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  permission_handler: ^11.4.0
  cupertino_icons: ^1.0.2
  pdf: ^3.10.1
  printing: ^5.9.1
  path_provider: ^2.1.1
  intl: ^0.18.1
  collection: ^1.17.1
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
